name: PHP Composer

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    if: "startsWith(github.event.head_commit.message, 'version')"

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP version
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.3

    - name: Install Composer dependencies
      run: composer install

    - name: Install NPM dependencies
      run: |
          chmod +x ./travis.sh
          ./travis.sh -t npm
          
    - name: Compile static files
      run: ./travis.sh -t build
      
    - name: Build a package
      run: ./travis.sh -t pack
      env:
        PRODUCT_NAME: ${{ secrets.PRODUCT_NAME }}

    - name: Upload main package
      run: ./travis.sh -t upload
      env:
        PRODUCT_NAME: ${{ secrets.PRODUCT_NAME }}
        FTP_USER: ${{ secrets.FTP_USER }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}

    - name: PLESK - Set permission for package builder
      run: chmod +x ./travis-plesk-builder.sh
          
    - name: PLESK - Compile static files 
      run: ./travis-plesk-builder.sh -t build
      env:
        PRODUCT_NAME: ${{ secrets.PRODUCT_NAME }}
        PLESK_PRODUCT_TITLE: "WebMail Pro"
        PLESK_PRODUCT_FULLTITLE: "AfterLogic WebMail Pro"
        PLESK_PRODUCT_WEBSITE: "https://www.afterlogic.com/webmail-client"
        PLESK_PRODUCT_DOWNLOAD: "https://www.afterlogic.com/download/webmail-pro"

    - name: PLESK - Generate changelog
      run: ./travis-plesk-builder.sh -t log
      
    - name: PLESK - Build a package
      run: ./travis-plesk-builder.sh -t zip
      env:
        PRODUCT_NAME: ${{ secrets.PRODUCT_NAME }}

    - name: PLESK - Upload plesk package
      run: ./travis-plesk-builder.sh -t upload
      env:
        PRODUCT_NAME: ${{ secrets.PRODUCT_NAME }}
        FTP_USER: ${{ secrets.FTP_USER }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}